#!/bin/bash

set -euo pipefail

######### CONFIG ##########
USER=""
DISK_UUID=
GLOBAL_FLAGS="-q"
MOUNT_POINT="/media/wd"
LOG_FILE="/home/$USER/logs/restic.log"
HEALTHCHECK_URL=""
export RESTIC_REPOSITORY="$MOUNT_POINT/restic"
export RESTIC_PASSWORD_FILE=""

###########################

curl -fsS -m 10 --retry 5 -o /dev/null "${HEALTHCHECK_URL}/start"
echo "-----------------------------------------------"
echo "Starting backup process at $(date '+%Y-%m-%d %H:%M:%S')." | tee -a $LOG_FILE

if [ ! -e /dev/disk/by-uuid/$DISK_UUID ] ; then
	echo "Backup disk not found! Exiting..." 2>&1 | tee -a $LOG_FILE
	exit 1
fi

echo "Mounting backup disk..."
mount -a	# ensure disk is added to /etc/fdisk

# pre-backup check
restic $GLOBAL_FLAGS check | tee -a $LOG_FILE

# start backup
echo "Performing backups..."
restic $GLOBAL_FLAGS backup "/home/$USER" --exclude "/home/$USER/logs"

# post-backup check
restic $GLOBAL_FLAGS check | tee -a $LOG_FILE

# clean up old snapshots
echo "Cleaning old snapshots..."
restic $GLOBAL_FLAGS forget -d 7 -w 4 -m 3 -y 1 --prune

# final check
restic check | tee -a $LOG_FILE

echo "Unmounting backup disk..."
umount $MOUNT_POINT

echo "Backup completed at $(date '+%Y-%m-%d %H:%M:%S')." | tee -a $LOG_FILE
curl -fsS -m 10 --retry 5 -o /dev/null $HEALTHCHECK_URL 
exit 0
