---
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.2
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - WEBUI_PORT=6011
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ./config:/config
      - ./torrents:/downloads
    network_mode: "service:wireguard"

  wireguard:
    image: ghcr.io/linuxserver/wireguard:1.0.20250521
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ./wg:/config
      - /lib/modules:/lib/modules
    ports:
      - 6011:6011
      - 6881:6881
      - 6881:6881/udp
      - 51821:51820/udp
