---
services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:2.8.11-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "4433:443"
    environment:
      - CADDY_INGRESS_NETWORKS=proxy
    volumes:
      - ./caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  actual:
    container_name: actual
    image: ghcr.io/actualbudget/actual-server:24.4.0-alpine
    environment:
      - userFilesPath=./user-files
      - serverFilesPath=./server-files
      - externalPort=5006
    restart: unless-stopped
    labels:
      caddy: localhost
      caddy.reverse_proxy: "{{ upstreams 5006 }}"
    networks:
      - proxy

networks:
  proxy:
    external: true
