---
version: "3.1"
services:
  paperless-ng:
    image: lscr.io/linuxserver/paperless-ng:1.5.0
    container_name: paperless-ng
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - REDIS_URL= #optional
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8000:8000
    networks:
      - npm-reverseproxy

networks:
  npm-reverseproxy:
    external: true
