version: "3"

services:
    drone-server:
        image: drone/drone:latest
        container_name: drone-server
        restart: unless-stopped
        env_file: drone.env
        volumes:
          - ./drone:/data
        networks:
          - npm-reverseproxy

    drone-runner-docker:
        image: drone/drone-runner-docker:1
        container_name: drone-runner-docker
        restart: unless-stopped
        depends_on: 
          - drone-server
        env_file: drone.env
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

networks:
  npm-reverseproxy:
    external: true
