---
version: "3.6"

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:${DRONE_IMG_VER:-latest}
    restart: unless-stopped
    env_file: ${DRONE_ENV_FILE:-drone.env}
    volumes:
      - ${DRONE_DATA_DIR:-./drone}:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.drone-proxy.entrypoints=https"
      - "traefik.http.routers.drone-proxy.rule=Host(`drone.${DOMAIN_NAME}`)"
      - "traefik.http.routers.drone-proxy.tls=true"
      - "traefik.http.routers.drone-proxy.service=drone-service"
      - "traefik.http.services.drone-service.loadbalancer.server.port=80"
      # - "traefik.http.routers.drone-router.middlewares=chain-authelia@file"

  drone-runner-docker:
    container_name: drone-runner-docker
    image: drone/drone-runner-docker:1
    restart: unless-stopped
    depends_on:
      - drone-server
    env_file: drone.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true
