---
version: '3.6'
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:4.33
    user: "${CUID:-1000}:${CGID:-1000}"
    restart: unless-stopped
    environment:
      - "TZ=${TZ:-Asia/Singapore}"
    volumes:
      - "${AUTHELIA_CONFIG_DIR:-./config}:/config"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.authelia-proxy.entrypoints=https"
      - "traefik.http.routers.authelia-proxy.rule=Host(`auth.${DOMAIN_NAME}`)"
      - "traefik.http.routers.authelia-proxy.tls=true"
#      - "traefik.http.routers.authelia-proxy.middlewares=chain-authelia@file"
      - "traefik.http.routers.authelia-proxy.service=authelia-service"
      - "traefik.http.services.authelia-service.loadbalancer.server.port=${AUTHELIA_PORT:-9091}"

networks:
  proxy:
    external: true
