version: '3.4'
services:

  db:
    container_name: miniflux_db
    image: postgres:latest
    env_file: miniflux.env
    user: 1000:1000
    volumes:
      - ./miniflux-db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    networks:
      - miniflux

  miniflux:
    container_name: "${MF_CONTAINER_NAME:-miniflux}"
    image: miniflux/miniflux:2.0.35
    env_file: miniflux.env
    restart: unless-stopped
    #ports:
      #- "127.0.0.1:${MF_PORT:-8120}:8120"
    depends_on:
      - db
    healthcheck:
      # test: ["CMD", "wget", "--spider", "localhost:8120"]
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
      interval: 60s
      start_period: 30s
    networks:
      - miniflux
      - npm-reverseproxy

networks:
  miniflux:
    name: miniflux
  npm-reverseproxy:
    external: true
