---
version: '3.6'
services:

  db:
    container_name: miniflux_db
    image: postgres:latest
    user: ${CUID:-1000}:${CGID:-1000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    env_file: ${MINIFLUX_DB_ENV_FILE:-miniflux.env}
    volumes:
      - ${MINIFLUX_DB_DIR:-./miniflux-db}:/var/lib/postgresql/data
    networks:
      - miniflux

  miniflux:
    container_name: "miniflux"
    image: miniflux/miniflux:${MINIFLUX_IMG_VER:-2.0.35}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
      interval: 60s
      start_period: 30s
    depends_on:
      - db
    env_file:
      - "${MINIFLUX_ENV_FILE:-./miniflux.env}"
    environment:
      - PORT=8120
      - DEBUG=1
      - RUN_MIGRATIONs=1
      - CREATE_ADMIN=1
    # ports:
    #  - "127.0.0.1:${MF_PORT:-8120}:8120"
    networks:
      - miniflux
      - npm-reverseproxy

networks:
  miniflux:
    name: miniflux
  npm-reverseproxy:
    external: true
