version: "3"

services:
    gitea:
        image: gitea/gitea:latest
        container_name: gitea
        restart: unless-stopped
        environment:
            - USER_UID=1000
            - USER_GID=1000
        volumes:
            - ./gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            # - 3000:3000
            - 2222:22
        networks:
          - npm-reverseproxy

networks:
  npm-reverseproxy:
    external: true
