---
version: "3.6"

services:
  gitea:
    image: gitea/gitea:${GITEA_IMG_VER:-latest}
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=${CUID:-1000}
      - USER_GID=${CGID:-1000}
    volumes:
      - ${GITEA_DATA_DIR:-./gitea}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - 3000:3000
      - 2222:22
    networks:
      - proxy

networks:
  proxy:
    external: true
