---
version: "3.6"

services:
  gitea:
    image: gitea/gitea:${GITEA_IMG_VER:-latest}
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=${CUID:-1000}
      - USER_GID=${CGID:-1000}
    volumes:
      - ${GITEA_DATA_DIR:-./gitea}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - 3000:3000
      - 2222:22
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.gitea-proxy.entrypoints=https"
      - "traefik.http.routers.gitea-proxy.rule=Host(`git.${DOMAIN_NAME}`)"
      - "traefik.http.routers.gitea-proxy.tls=true"
      - "traefik.http.routers.gitea-proxy.service=gitea-service"
      - "traefik.http.services.gitea-service.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
