---
global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true

log:
  level: "DEBUG"

accessLog:
  filePath: "/traefik.log"
  filters:
    statusCodes: "400-499"

entrypoints:
  http:
    address: :80
  https:
    address: :443

providers:
  docker:
    network: "proxy"  # docker network name
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service" }}.{{ env "DOMAIN_NAME"}}`)'

  # file:
    # directory: "/rules"

certificatesResolvers:
  dns-dgo:
    acme:
#      email: '{{ env "CA_EMAIL"}}'
      storage: "acme.json"
#      caServer: '{{ env "CA_SERVER"}}'
      dnsChallenge:
        provider: digitalocean
        resolvers: "1.1.1.1:53,1.0.0.1:53"

