version: '3.6'
services:
  calibre-web:
    container_name: calibre-web
    image: "lscr.io/linuxserver/calibre-web:${CALIBRE_WEB_IMG_VER:-amd64-0.6.18}"
    restart: unless-stopped
    environment:
      - PUID=${CUID:-1000}
      - PGID=${CGID:-1000}
      - TZ=${TZ:-Asia/Singapore}
    volumes:
      - "${CALIBRE_WEB_CONFIG_DIR:-./config}:/config"
      - "${CALIBRE_WEB_LIB_DIR:-./books}:/books"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.calibre-proxy.entrypoints=https"
      - "traefik.http.routers.calibre-proxy.rule=Host(`books.${DOMAIN_NAME}`)"
      - "traefik.http.routers.calibre-proxy.tls=true"
#      - "traefik.http.routers.calibre-proxy.tls.certresolver=dns-dgo"
      - "traefik.http.routers.calibre-proxy.service=calibre-service"
      - "traefik.http.services.calibre-service.loadbalancer.server.port=${CALIBRE_WEB_PORT:-8083}"

networks:
  proxy:
    external: true
