---
version: "3.6"
services:
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:${CALIBRE_WEB_IMG_VER:-arm64v8-0.6.15}
    restart: unless-stopped
    environment:
      - PUID=${CUID:-1000}
      - PGID=${CGID:-1000}
      - TZ=${TZ:-Asia/Singapore}
    volumes:
      - ${CALIBRE_WEB_CONFIG_DIR:-./config}:/config
      - "${CALIBRE_WEB_LIB_DIR:-./books}:/books"
    # ports:
    #   - "127.0.0.1:${CALIBRE_WEB_PORT:-8083}:8083"
    networks:
      - npm-reverseproxy

networks:
  npm-reverseproxy:
    external: true
