---
version: "3.1"
services:
  paperless-redis:
    image: redis:6.0
    container_name: paperless-redis
    restart: unless-stopped
    networks:
      - paperless

  paperless-ng:
    image: ghcr.io/paperless-ngx/paperless-ngx:${PAPERLESS_IMG_VER:-1.7.1}
    container_name: paperless-ngx
    restart: unless-stopped
    depends_on:
      - paperless-redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 120s
      start_period: 30s
      timeout: 10s
      retries: 5
    env_file: paperless.env
    environment:
      - USERMAP_UID=${CUID:-1000}
      - USERMAP_GID=${CGID:-1000}
      - PAPERLESS_TIME_ZONE=${TZ:-Asia/Singapore}
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_URL=https://paper.${DOMAIN_NAME}
    volumes:
      - "${PAPERLESS_DATA_DIR:-./data}:/usr/src/paperless/data"
      - "${PAPERLESS_CONSUME_DIR:-./consume}:/usr/src/paperless/consume"
      - "${PAPERLESS_MEDIA_DIR:-./media}:/usr/src/paperless/media"
    networks:
      - proxy
      - paperless
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.paperless-proxy.entrypoints=https"
      - "traefik.http.routers.paperless-proxy.rule=Host(`paper.${DOMAIN_NAME}`)"
      - "traefik.http.routers.paperless-proxy.tls=true"
      - "traefik.http.routers.paperless-proxy.service=paperless-service"
      - "traefik.http.services.paperless-service.loadbalancer.server.port=${PAPERLESS_PORT:-8000}"
      # - "traefik.http.routers.paperless-router.middlewares=chain-authelia@file"

networks:
  proxy:
    external: true
  paperless:
    name: paperless
