version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:1.8.5
    #ports:
      #- "127.0.0.1:${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - linkding.env
    restart: unless-stopped
    networks:
      - npm-reverseproxy

networks:
  npm-reverseproxy:
    external: true
