---
version: '3.6'
services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:${LINKDING_IMG_VER:-1.8.5}
    user: "${CUID:-1000}:${CGID:-1000}"
    restart: unless-stopped
    env_file:
      - "${LINKDING_ENV_FILE:-linkding.env}"
    volumes:
      - "${LINKDING_DATA_DIR:-./data}:/etc/linkding/data"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.linkding-proxy.entrypoints=https"
      - "traefik.http.routers.linkding-proxy.rule=Host(`linkding.${DOMAIN_NAME}`)"
      - "traefik.http.routers.linkding-proxy.tls=true"
      - "traefik.http.routers.linkding-proxy.service=linkding-service"
      - "traefik.http.services.linkding-service.loadbalancer.server.port=${LINKDING_PORT:-9090}"

networks:
  proxy:
    external: true
