---
version: '3.6'
services:
  pigallery2:
    image: bpatrik/pigallery2:2.0.0-alpine
    container_name: pigallery2
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - "./config:/app/data/config"
      - "./data:/app/data/db"
      - "./images:/app/data/images:ro"
      - "./tmp:/app/data/tmp"
    ports:
      - 8080:80
