---
version: "3.6"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:6.17.0
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ./config:/config
      - ~/syncthing/sync/books:/library
      - ./import:/import
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped
