version: '3.3'

services:
  app:
    container_name: firefly
    image: fireflyiii/core:version-5.6.14
    restart: unless-stopped
    env_file: firefly.env
    volumes:
      - "${FIREFLY_DATA_DIR:-./data}:/var/www/html/storage/upload"
    ports:
      - "127.0.0.1:${FIREFLY_PORT:-8080}:8080"
    depends_on:
      - db
    networks:
      - firefly
      - npm-reverseproxy

  db:
    container_name: fireflydb
    image: mariadb    
    restart: unless-stopped
    env_file: fireflydb.env
    user: 1000:1000
    volumes:
      - "${FIREFLY_DB_DIR:-./db}:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      start_period: 30s
      retries: 5
    networks:
      - firefly

networks:
  firefly:
    name: firefly
  npm-reverseproxy:
    external: true
