---
version: '3.6'
services:
  db:
    container_name: fireflydb
    image: mariadb
    user: "${CUID:-1000}:${CGID:-1000}"
    restart: unless-stopped
    env_file: "${FIREFLY_DB_ENV_FILE:-fireflydb.env}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      start_period: 30s
      retries: 5
    volumes:
      - "${FIREFLY_DB_DIR:-./db}:/var/lib/mysql"
    networks:
      - firefly

  app:
    container_name: firefly
    image: fireflyiii/core:${FIREFLY_IMG_VER:-version-5.7.6}
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    env_file: "${FIREFLY_ENV_FILE:-firefly.env}"
    depends_on:
      - db
    volumes:
      - "${FIREFLY_DATA_DIR:-./data}:/var/www/html/storage/upload"
    networks:
      - proxy
      - firefly
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.firefly-proxy.entrypoints=https"
      - "traefik.http.routers.firefly-proxy.rule=Host(`firefly.${DOMAIN_NAME}`)"
      - "traefik.http.routers.firefly-proxy.tls=true"
      - "traefik.http.routers.firefly-proxy.service=firefly-service"
      - "traefik.http.services.firefly-service.loadbalancer.server.port=${FIRFLY_PORT:-8080}"
      # - "traefik.http.routers.firefly-proxy.middlewares=chain-authelia@file"

networks:
  firefly:
    name: firefly
  proxy:
    external: true
