version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.11.0
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${PORTAINER_DATA_DIR:-./data}:/data"
    ports:
      - "127.0.0.1:${PORTAINER_PORT:-9443}:9443"
    networks:
      - npm-reverseproxy

networks:
  npm-reverseproxy:
    external: true

