---
version: "3.6"
services:
  minio:
    container_name: minio
    image: "quay.io/minio/minio:latest"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data:/data"
    restart: unless-stopped
