---
version: "3.6"
services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:${SYNCTHING_IMG_VER:-1.19.0}
    restart: unless-stopped
    environment:
      - "PUID=${CUID:-1000}"
      - "PGID=${CGID:-1000}"
      - "TZ=${TZ:-Asia/Singapore}"
    volumes:
      - "${SYNCTHING_CONFIG_DIR:-./config}:/config"
      - "${SYNCTHING_DATA_DIR:-./sync}:/data"
    ports:
      - 22000:22000/tcp  # listening port
      - 21027:21027/udp  # protocol discovery
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.syncthing-proxy.entrypoints=https"
      - "traefik.http.routers.syncthing-proxy.rule=Host(`syncthing.${DOMAIN_NAME}`)"
      - "traefik.http.routers.syncthing-proxy.tls=true"
      - "traefik.http.routers.syncthing-proxy.service=syncthing-service"
      - "traefik.http.services.syncthing-service.loadbalancer.server.port=${SYNCTHING_PORT:-8384}"
      - "traefik.http.routers.syncthing-proxy.middlewares=chain-authelia@file"

networks:
  proxy:
    external: true
