---
version: "3"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.18.5
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - "${SYNCTHING_CONFIG_DIR:-./config}:/config"
      - "${SYNCTHING_DATA_DIR:-./sync}:/data"
    ports:
      #- 127.0.0.1:8384:8384
      - 22000:22000/tcp
      - 21027:21027/udp
    restart: unless-stopped
    networks:
      - npm-reverseproxy

networks:
  npm-reverseproxy:
    external: true
