version: '3.5'

services:
  photoprismdb:
    image: arm64v8/mariadb:10.6 # this mariadb image runs on ARM64-based devices only
    container_name: photoprismdb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    env_file: "${PHOTOPRISMDB_ENV_FILE:-photoprismdb.env}"
    volumes:
      - "${PHOTOPRISM_DB_DIR:-./database}:/var/lib/mysql"
    networks:
      - photoprism

  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:${PHOTOPRISM_IMG_VER:-20220121}
    restart: unless-stopped
    depends_on:
      - photoprismdb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    user: "${CUID:-1000}:${CGID:-1000}"
    env_file: "${PHOTOPRISM_ENV_FILE:-photoprism.env}"
    working_dir: "/photoprism"
    volumes:
      - "${PHOTOPRISM_PICS_DIR:-~/pictures}:/photoprism/originals"
      - "${PHOTOPRISM_STORAGE_DIR:-./storage}:/photoprism/storage"
    networks:
      - photoprism
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.photoprism-proxy.entrypoints=https"
      - "traefik.http.routers.photoprism-proxy.rule=Host(`photos.${DOMAIN_NAME}`)"
      - "traefik.http.routers.photoprism-proxy.tls=true"
      - "traefik.http.routers.photoprism-proxy.service=photoprism-service"
      - "traefik.http.services.photoprism-service.loadbalancer.server.port=${PHOTOPRISM_PORT:-2342}"
      - "traefik.http.routers.photoprism-router.middlewares=chain-authelia@file"

networks:
  photoprism:
    name: photoprism
  proxy:
    external: true
